import { createHmac, timingSafeEqual } from "crypto";
import bcrypt from "bcryptjs";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
const schema=z.object({email:z.string().email().max(254),password:z.string().min(8).max(200),remember:z.boolean().optional()});
const attempts=new Map<string,{count:number;start:number;blockedUntil?:number}>(); const failures=new Map<string,{count:number;lockedUntil?:number}>();
const b64=(value:string)=>Buffer.from(value).toString("base64url");
function token(email:string){const secret=process.env.ADMIN_SESSION_SECRET;if(!secret)throw new Error("ADMIN_SESSION_SECRET is not configured");const payload=b64(JSON.stringify({email,exp:Date.now()+86_400_000}));const sig=createHmac("sha256",secret).update(payload).digest("base64url");return `${payload}.${sig}`}
export async function POST(req:NextRequest){const ip=req.headers.get("x-forwarded-for")?.split(",")[0].trim()??"anonymous",now=Date.now(),rate=attempts.get(ip)??{count:0,start:now};if(rate.blockedUntil&&rate.blockedUntil>now)return NextResponse.json({error:"Temporarily blocked"},{status:429});if(now-rate.start>60_000){rate.count=0;rate.start=now}rate.count++;if(rate.count>5){rate.blockedUntil=now+15*60_000;attempts.set(ip,rate);console.warn("admin_rate_limited",{ip});return NextResponse.json({error:"Too many attempts"},{status:429})}attempts.set(ip,rate);try{const data=schema.parse(await req.json()),email=data.email.toLowerCase(),failure=failures.get(email);if(failure?.lockedUntil&&failure.lockedUntil>now)return NextResponse.json({error:"Account temporarily locked"},{status:429});const valid=email===process.env.ADMIN_EMAIL?.toLowerCase()&&!!process.env.ADMIN_PASSWORD_HASH&&await bcrypt.compare(data.password,process.env.ADMIN_PASSWORD_HASH);if(!valid){const next={count:(failure?.count??0)+1,lockedUntil:undefined as number|undefined};if(next.count>=10)next.lockedUntil=now+30*60_000;failures.set(email,next);console.warn("admin_login_failed",{email,ip});return NextResponse.json({error:"Invalid credentials"},{status:401})}failures.delete(email);const response=NextResponse.json({ok:true});response.cookies.set("admin_session",token(email),{httpOnly:true,secure:true,sameSite:"strict",path:"/",maxAge:data.remember?60*60*24*30:60*60*24});console.info("admin_login",{email,ip});return response}catch{return NextResponse.json({error:"Invalid request"},{status:400})}}
